models:
 "gpt-4o-mini": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "openai"  # or azure / ollama / groq etc.
   base_url: "https://api.openai.com/v1" 
   api_key: ""
   temperature: 0
 "anthropic/claude-3.5-sonnet": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
    api_type: "openai"
    base_url: "https://openrouter.ai/api/v1"
    api_key: ""
    temperature: 0
 "anthropic/claude-3.5-sonnet": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
    api_type: "openai"
    base_url: "https://openrouter.ai/api/v1"
    api_key: ""
    temperature: 0
 "gpt-4o": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "openai"  # or azure / ollama / groq etc.
   base_url: "https://api.openai.com/v1" 
   api_key: ""
   temperature: 0

llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "gpt-4o-mini"  # or gpt-3.5-turbo
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: ""
